version: '3.8'

volumes:
    temp_storage:

services:
    gesgen:
        build:
            context: ./src/ZeroEGGS/
            dockerfile: Dockerfile
        depends_on:
          - redis
        environment:
          - CELERY_BROKER_URL=${CELERY_BROKER_URL}
          - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
          - CELERY_WORKER_TIMEOUT=${CELERY_WORKER_TIMEOUT}
          - SERVER_MODE=${SERVER_MODE}
          - WORKER_COUNT_GESGEN=${WORKER_COUNT_GESGEN}
        image: wasp-ss2023-gesgen
        volumes:
          - './data:/app/data:ro'
          - './output:/app/output'
          - type: volume
            source: 'temp_storage'
            target: /shared_storage/
          - ./src/ZeroEGGS:/app/ZeroEGGS
    visual:
        build:
            context: ./src/genea_visualizer/
            dockerfile: Dockerfile
        image: wasp-ss2023-visual
        depends_on:
          - redis
        environment:
          - CELERY_BROKER_URL=${CELERY_BROKER_URL}
          - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
          - CELERY_WORKER_TIMEOUT=${CELERY_WORKER_TIMEOUT}
          - SERVER_MODE=${SERVER_MODE}
          - WORKER_COUNT_VISUAL=${WORKER_COUNT_VISUAL}
        volumes:
          - './data:/app/data:ro'
          - './output:/app/output'
          - type: volume
            source: 'temp_storage'
            target: /shared_storage/
          - ./src/genea_visualizer:/app/genea_visualizer
    web:
        build:
            context: ./src/app/
            dockerfile: Dockerfile
        depends_on:
          - redis
        environment: 
          - INTERNAL_WEB_PORT=${INTERNAL_WEB_PORT}
          - CELERY_BROKER_URL=${CELERY_BROKER_URL}
          - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
          - SERVER_MODE=${SERVER_MODE}
        image: wasp-ss2023-web
        ports:
          - ${PUBLIC_WEB_PORT}:${INTERNAL_WEB_PORT}
        volumes:
          - './data:/app/data:ro'
          - './output:/app/output'
          - type: volume
            source: 'temp_storage'
            target: /shared_storage/
          - ./src/app:/app
    redis:
        image: redis:7-alpine
