version: '3.8'

volumes:
    appdata:        
        name: 'appdata'
        driver: local
        driver_opts:
            type: none
            device: './data'
            o: 'bind'
    output:
        name: 'output'
        driver: local
        driver_opts:
            type: none
            o: 'bind'
            device: './output'
    temp_storage:

services:
    gesgen:
        build:
            context: ./src/ZeroEGGS/
            dockerfile: Dockerfile
        depends_on:
          - redis
        environment:
          - CELERY_BROKER_URL=${CELERY_BROKER_URL}
          - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
          - CELERY_WORKER_TIMEOUT=${CELERY_WORKER_TIMEOUT}
        image: wasp-ss2023-gesgen
        volumes:
          - type: volume
            source: 'appdata'
            target: /app/data/
            read_only: true
            volume:
                nocopy: true
          - type: volume
            source: 'output'
            target: /app/output/
            volume:
                nocopy: true
          - type: volume
            source: 'temp_storage'
            target: /shared_storage/
          - ./src/ZeroEGGS:/app/ZeroEGGS
    visual:
        build:
            context: ./src/genea_visualizer/celery-queue/
            dockerfile: Dockerfile
        image: wasp-ss2023-visual
        volumes:
          - type: volume
            source: 'appdata'
            target: /app/data/
            read_only: true
            volume:
                nocopy: true
          - type: volume
            source: 'output'
            target: /app/output/
            volume:
                nocopy: true
        tty: true
    web:
        build:
            context: ./src/app/
            dockerfile: Dockerfile
        depends_on:
          - redis
        environment: 
          - INTERNAL_WEB_PORT=${INTERNAL_WEB_PORT}
          - CELERY_BROKER_URL=${CELERY_BROKER_URL}
          - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
        image: wasp-ss2023-web
        ports:
          - ${PUBLIC_WEB_PORT}:${INTERNAL_WEB_PORT}
        volumes:
          - type: volume
            source: 'appdata'
            target: /app/data/
            read_only: true
            volume:
                nocopy: true
          - type: volume
            source: 'output'
            target: /app/output/
            volume:
                nocopy: true
          - type: volume
            source: 'temp_storage'
            target: /shared_storage/
          - ./src/app:/app
    redis:
        image: redis:7-alpine
